TheEdoRan/next-safe-action

README.md, src/hook.ts, src/index.ts
After calling `revalidatePath`, Next.js refreshes CSS via browser request. During this time interval, the initial state passed to `useOptimisticAction` hook is flashed. This PR forces the optimistic state type to be the same as `res.data` (action's return type), spreads the `res.data` object after `initialOptData`,  and renames `optimisticState` to `optimisticData`, which is less confusing, since types now match.
Closes #10
=> fix(hook): prevent initial data flashing, rename `optimisticState` to `optimisticData`

packages/example-app/src/app/hook/deleteuser-form.tsx, packages/example-app/src/app/optimistic-hook/addlikes-form.tsx, packages/next-safe-action/README.md, packages/next-safe-action/README_v2.md, packages/next-safe-action/src/hook.ts, packages/next-safe-action/src/types.ts
Hi Edoardo!
First of all, thanks a lot for this library, it's super handy when working with server actions :+1: 
I've opened a PR to add another parameter to the `onSuccess` and `onError` callbacks, which contains the original input as it's sent to the server. This is handy whenever the server is not returning all the expected data, or the error callback is called, but the client still needs the input data to do something (for instance, render a toast containing a message).
Example:
```ts
const { execute } = useAction(
sendEmail,
{
onError: (_, _, input) => {
toast({
title: `Error while sending an email to: ${input.email}`,
});
},
},
);
const handleSendEmal = (email: string) => {
execute({ email: email });
};
```
Without the `input` parameter, there is no way for me to get access to the …
=> feat(hooks): add input parameter to callbacks

packages/example-app/src/app/hook/deleteuser-form.tsx, packages/example-app/src/app/optimistic-hook/addlikes-form.tsx, packages/next-safe-action/README.md, packages/next-safe-action/src/hook.ts, packages/next-safe-action/src/types.ts
Inspired by [react-query](https://tanstack.com/query/latest/docs/react/overview)'s `onMutate` I added the callback `onExecute` to both hooks `useAction` and `useOptimisticAction`. This callback is useful to run code before any action and avoid creating an extra helper function. The input can be accessed aswell in order to perform different actions based on it
**Before**
```typescript
const action = useAction(myAction)
const mutate = () => {
console.log("I really want to print this on action execution");
action.execute();
}
return <button onClick={mutate}>hello</button>
```
**After**
```typescript
const action = useAction(myAction, {
onExecute(input) {
console.log("I really want to print this on action execution", input);
}
})
return <button onClick={action.execute}>hello</button>
```
=> Add onExecute callback

packages/next-safe-action/src/hook.ts, packages/next-safe-action/src/server.ts, packages/next-safe-action/src/types.ts, packages/next-safe-action/src/utils.ts, packages/website/docs/types.md, packages/website/docs/usage-from-client/hooks/callbacks.md
- Update the `isNextRedirectError` and `isNextNotFoundError` methods to be identical to the Next.js internals.
- Update the `useAction` and `useOptimisticAction` hooks to use a default result state and not set an undefined result, as can happen when handling the `NEXT_REDIRECT` or `NEXT_NOT_FOUND` responses.
=> fix(hooks): fix handling Next redirects and 404s

website/docs/usage-with-forms.md
Fixed a minor typo in the docs. Zod library should be imported, because the schema that is being defined in this example uses validators that are from it.
=> docs(website): fixed missing zod import

packages/example-app/src/lib/safe-action.ts
The middleware doesn't return userId eventhough it's used in the action
=> fix(example): return userId from middleware

packages/example-app/src/app/login-action.ts, packages/example-app/src/app/with-context/edituser-action.ts, packages/example-app/src/lib/safe-action.ts, packages/next-safe-action/src/index.ts, packages/next-safe-action/src/utils.ts
I've encountered in almost every project that interacts with an external API a need to return a validation error from the server action. Common example could be when creating a new record that has a unique key (for example email). The server action calls the API and get an error that the email already exists. I usually hacked this and returned a response from server action in similar format to:
```json
{
"success": false,
"errors": {
"email": "Email already exists"
}
}
```
Then on client side, there's a need for an additional check on the returned data.
This PR aims to add a way for the user to trigger `validationErrors` output from the server action, instead of the described approach above, there's new function passed to the server action, that lets you trigger the `valdiationErrors`. …
=> feat(servervalidationerror): adds a ServerValidationError

packages/next-safe-action/src/index.ts, website/docs/safe-action-client/using-a-middleware.md, website/docs/types.md
This PR adds the ability to pass additional arguments from the action builder to the middleware. This is especially useful when you want to handle the auth logic inside the middleware and you need to check if user has specific roles or permissions to execute the function. I have created a small example of how this feature would be used. 
```ts
// action.ts
export const deleteUser = action(schema, async ({ id }) => {
// an actual logic...
}, { role: "admin" });
// safeAction.ts
export const authAction = createSafeActionClient({
async middleware(parsedInput, additionalArguments) {
const session = cookies().get("session")?.value;
if (!session) {
throw new Error("Session not found!");
}
// In the real world, you would check if the session is valid by querying a database.
// We'll keep it very …
```
=> feat: support passing data to middleware from actions

package-lock.json, packages/example-app/package.json, packages/next-safe-action/package.json, packages/next-safe-action/src/hooks.ts, packages/next-safe-action/src/index.ts, packages/next-safe-action/src/utils.ts, website/docs/getting-started.md
This PR upgrades TypeSchema from v0.12 to v0.13. v0.13 is a major refactor of the library, which switched to a modular design. From now on, next-safe-action will use @typeschema/main to just include the common adapter logic without actually bundling adapters. This keeps the bundle size small, while allowing users to choose the specific validation libraries (and adapters) they want to use.
=> refactor: upgrade TypeSchema to v0.13

packages/next-safe-action/src/index.ts, packages/next-safe-action/src/validation-errors.ts, packages/next-safe-action/src/validation-errors.types.ts
Sometimes it's better to deal with a flattened error object instead of a formatted one, for instance when you don't need to use nested objects in validation schemas.
This PR exports a function called `flattenValidationErrors` that does what it says. Be aware that it works just one level deep, as it discards nested schema errors. This is a known limitation of this approach, since it can't prevent key conflicts.
Suppose this is a returned formatted `validationErrors` object: 
```typescript
validationErrors = {
_errors: ["Global error"],
username: {
_errors: ["Too short", "Username is invalid"],
},
email: {
_errors: ["Email is invalid"],
}
}
```
After passing it to `flattenValidationErrors`:
```typescript
import { flattenValidationErrors } from "next-safe-action";
const flattenedErrors = …
```
=> feat(validation-errors): support flattening via `flattenValidationErrors` function

packages/example-app/src/app/(examples)/empty-schema/empty-action.ts, packages/example-app/src/app/(examples)/empty-schema/page.tsx, packages/example-app/src/app/page.tsx, packages/next-safe-action/src/hooks.ts, packages/next-safe-action/src/hooks.types.ts, packages/next-safe-action/src/index.ts, packages/next-safe-action/src/index.types.ts, packages/next-safe-action/src/validation-errors.ts, packages/next-safe-action/src/validation-errors.types.ts, website/docs/safe-action-client/instance-methods.md, website/docs/types.md
This PR adds the ability to omit passing a validation schema to the `schema` method.
=> feat: allow omitting schema argument in `schema` method

apps/playground/src/lib/safe-action.ts, packages/next-safe-action/package.json, packages/next-safe-action/src/action-builder.ts, packages/next-safe-action/src/safe-action-client.ts, packages/next-safe-action/src/zod.ts, packages/next-safe-action/tsup.config.ts, pnpm-lock.yaml, website/docs/contributing.md, website/docs/getting-started.md, website/docs/migrations/index.md, website/docs/troubleshooting/errors-with-typeschema.md, website/docs/troubleshooting/index.md
Sometimes, TypeSchema causes errors with its dynamic import system, to handle multiple validation libraries.
The code in this PR exports a copy of the safe action client from the `/zod` path, that support just Zod validation library, as the name implies. This should fix problems with the edge runtime and hopefully future bundler issues too.
=> feat(action-client): export a copy of safe action client from `/zod` path

apps/playground/src/app/(examples)/optimistic-hook/addtodo-action.ts, apps/playground/src/app/(examples)/optimistic-hook/addtodo-form.tsx, apps/playground/src/app/(examples)/optimistic-hook/page.tsx, packages/next-safe-action/src/hooks.ts, website/docs/execution/hooks/useoptimisticaction.md
This PR improves the design of the `useOptimisticAction` hook. Previously, the `optimisticData`  had to be of the same type of action's return type. This isn't great, because the only job of a Server Action in a optimistic workflow is to mutate the data on the server. The actual state (and type) that matters is the one coming from the parent Server Component, so `updateFn`'s `prevState` should match that type. The actual result is still available in hooks callbacks and `result` property returned from the hook,  though.
re #127
=> refactor(hooks): use separate type for server state in `useOptimisticAction`

apps/playground/src/app/(examples)/direct/login-action.ts, packages/next-safe-action/src/action-builder.ts, packages/next-safe-action/src/index.ts, packages/next-safe-action/src/index.types.ts, packages/next-safe-action/src/safe-action-client.ts, packages/next-safe-action/src/typeschema.ts, packages/next-safe-action/src/validation-errors.types.ts, website/docs/migrations/v6-to-v7.md, website/docs/recipes/customize-validation-errors-format.md, website/docs/safe-action-client/initialization-options.md, website/docs/safe-action-client/instance-methods.md, website/docs/types.md
Code in this PR adds the support for setting a default validation errors shape (formatted or flattened) per-instance. The shape is then overridable in `schema` and `bindArgsSchemas` methods, using `handleValidationErrorsShape` and `handleBindArgsValidationErrorsShape` optional functions.
=> feat: support setting default validation errors shape per instance

apps/playground/src/app/(examples)/async-schema/login-action.ts, apps/playground/src/app/(examples)/async-schema/page.tsx, apps/playground/src/app/page.tsx, packages/next-safe-action/.eslintrc.js, packages/next-safe-action/src/action-builder.ts, packages/next-safe-action/src/index.ts, packages/next-safe-action/src/safe-action-client.ts, packages/next-safe-action/src/typeschema.ts, packages/next-safe-action/src/validation-errors.ts, website/docs/migrations/v6-to-v7.md, website/docs/recipes/additional-validation-errors.md, website/docs/recipes/i18n.md, website/docs/safe-action-client/instance-methods.md
The code in this PR adds the support for passing a schema to the action via an async function inside the `schema` method. This is necessary, for instance, when you're using a i18n solution that requires to await the translations and pass them to schemas, as discussed in #111.
=> feat: support passing schema via async function

packages/next-safe-action/src/__tests__/action-callbacks.test.ts, packages/next-safe-action/src/__tests__/typeschema/action-callbacks.test.ts, packages/next-safe-action/src/action-builder.ts, packages/next-safe-action/src/index.types.ts, packages/next-safe-action/src/safe-action-client.ts, website/docs/execution/action-callbacks.md
This PR adds `ctx` and `metadata` props to `onSuccess`, `onError` and `onSettled` action callbacks.
=> refactor: add `ctx` and `metadata` props to action callbacks

website/src/components/landing/getting-started.tsx
chore(website): Currently, the "Explore example" link on the homepage takes users to a 404 Not Found page. I have updated the link to take users to the Recipes -> Playground page instead.
N/A
---
=> chore(website): Fix 404 link

packages/next-safe-action/src/__tests__/happy-path.test.ts, packages/next-safe-action/src/__tests__/typeschema/happy-path.test.ts, packages/next-safe-action/src/__tests__/typeschema/validation-errors.test.ts, packages/next-safe-action/src/__tests__/validation-errors.test.ts, packages/next-safe-action/src/action-builder.ts, packages/next-safe-action/src/index.ts, packages/next-safe-action/src/index.types.ts, packages/next-safe-action/src/safe-action-client.ts, packages/next-safe-action/src/typeschema.ts, packages/next-safe-action/src/validation-errors.ts, website/docs/recipes/additional-validation-errors.md, website/docs/recipes/customize-validation-errors-format.md, website/docs/recipes/extend-base-client.md, website/docs/recipes/extend-previous-schema.md, website/docs/recipes/form-actions.md, website/docs/recipes/i18n.md, website/docs/recipes/upload-files.md, website/docs/safe-action-client/index.md, website/docs/safe-action-client/initialization-options.md
This PR adds the support for:
1. Throwing validation errors with a `throwValidationErrors` config option passed to `createSafeActionClient`;
2. Extend schema by adding a `prevSchema` argument to the function passed to `schema` method.
1. #171
2. #173
=> v7.1.0 - `throwValidationErrors` and schema extension

packages/next-safe-action/src/action-builder.ts, packages/next-safe-action/src/index.ts, packages/next-safe-action/src/index.types.ts, packages/next-safe-action/src/safe-action-client.ts, packages/next-safe-action/src/typeschema.ts, website/docs/safe-action-client/initialization-options.md, website/docs/types.md
This PR adds util props as the second argument of `handleReturnedServerError` and `handleServerErrorLog` optional init functions. Now you have access to `clientInput`, `bindArgsClientInputs`, `ctx`, `metadata` and also `returnedError` (just for `handleServerErrorLog`), which is the server error customized by `handleReturnedServerError` function.
re #177
=> refactor: pass util props to `handleReturnedServerError` and `handleServerErrorLog`

website/docs/safe-action-client/middleware.md
Since this is being imported to another file, its good idea to export it
Add `export` statement in example code
=> chore(website): export `authActionClient` in middleware example

apps/playground/package.json, apps/playground/src/app/(examples)/hook/page.tsx, packages/next-safe-action/src/hooks-utils.ts, packages/next-safe-action/src/hooks.ts, packages/next-safe-action/src/stateful-hooks.ts, pnpm-lock.yaml, website/docs/execution/hooks/check-action-status.md, website/docs/execution/hooks/hook-callbacks.md, website/docs/execution/hooks/useaction.md, website/docs/execution/hooks/useoptimisticaction.md, website/docs/execution/hooks/usestateaction.md
This PR introduces a workaround for the issues described in #227, by adding `isTransitioning` and `isPending` shorthand statuses to the hooks return object. `isTransitioning` is the value returned from the `useTransition` hook that is used under the hood, while `isPending` has the value of `isExecuting || isTransitioning`, for convenience.
re #227
=> fix(hooks): add `isTransitioning` and `isPending` shorthand statuses to return object

packages/next-safe-action/src/hooks-utils.ts, packages/next-safe-action/src/hooks.ts, packages/next-safe-action/src/hooks.types.ts, packages/next-safe-action/src/index.types.ts, packages/next-safe-action/src/stateful-hooks.ts, website/docs/types.md, website/docs/types/index.md, website/docs/types/infer-types.md
Code in this PR adds and exports infer utility types for safe action client, middleware functions, safe actions and hooks.
re #233
=> refactor(types): export infer utility types

packages/next-safe-action/src/hooks-utils.ts, packages/next-safe-action/src/hooks.ts, packages/next-safe-action/src/hooks.types.ts
Code in this PR removes the `fetchError` prop from hook return object. Now the returned object is of type `SafeActionResult`. This means that if an error gets thrown inside an action, and the `handleServerError` init option rethrows it instead of setting the `serverError` prop, now the `execute`/`executeAsync` functions will throw it too inside the component, so the handling is managed by the user. This is the same behavior as directly calling a throwable safe action inside the component.
=> refactor: remove additional `fetchError` prop from hook return object

packages/next-safe-action/src/action-builder.ts, packages/next-safe-action/src/safe-action-client.ts, packages/next-safe-action/src/validation-errors.types.ts, website/docs/define-actions/validation-errors.md
Code in this PR adds a second argument to `handleValidationErrorsShape` and `handleBindArgsValidationErrorsShape` functions, called `utils`, which is an object that contains `clientInput`, `bindArgsClientInputs`, `metadata` and `ctx` properties. This addition allows you to set dynamic validation errors based on current action execution data.
re #256
=> refactor: pass utils to validation errors shape customizer functions

packages/next-safe-action/src/index.types.ts
Includes the `SafeActionClient` into the types export to make the inferred type of `createSafeActionClient` portable in order to avoid the error [TS2742](https://typescript.tv/errors/#ts2742). It enables declaring the action client in a shared package and import it in the other apps or packages.
Put your proposed changes here.
I've just exported the type in the `index.types.ts` file.
---
=> fix: export `SafeActionClient` type to make it portable

packages/next-safe-action/src/index.types.ts
Includes the `SafeActionClient` into the types export to make the inferred type of `createSafeActionClient` portable in order to avoid the error [TS2742](https://typescript.tv/errors/#ts2742). It enables declaring the action client in a shared package and import it in the other apps or packages.
closes #64
=> fix: export `SafeActionClient` type to make it portable (#267)

packages/next-safe-action/src/validation-errors.types.ts
`returnValidationErrors()` typechecking fails when a property is a primitive-object-intersection type (typical case of branded type). 
`returnValidationErrors()` refers to `type SchemaErrors<S>` for typings
the purpose of `type SchemaErrors<S>` as is:
```
type SchemaErrors<S> = {
[K in keyof S]?: S[K] extends object | null | undefined 
? Prettify<VEList & SchemaErrors<S[K]>> 
: VEList;
} & {};
```
is to map `S` properties conditionally:
if property `S[K]`  is `object | null | undefined`  maps to `Prettify<VEList & SchemaErrors<S[K]>>` 
else (property `S[K]`  is primitive)  maps to `VEList`
the issue arises when property `S[K]` is a branded primitive type.
Branded primitive types are typically an intersection of a primitive with an object holding the brand 
(e.g. `type email = string & { …
=> fix(validation-errors): type inference for branded, nullable, optional and array types

packages/next-safe-action/src/action-builder.ts, packages/next-safe-action/src/hooks.types.ts, packages/next-safe-action/src/index.types.ts
allows hook callbacks to call functions that have a return value other than void without wrapping in a closure. E.g. `onSuccess: () => toast.success('...')` where `toast.success` returns the toast id. I understand that the return value of the callback isn't used for anything but this allows for slightly cleaner code imo.
---
=> refactor(types): less strict callbacks return type

packages/next-safe-action/src/__tests__/middleware.test.ts, packages/next-safe-action/src/action-builder.ts, packages/next-safe-action/src/next/errors/index.ts
Although #303 has been resolved, I had also been investigating the same issue. During my analysis, I noticed that framework errors were not being caught in the most appropriate location, resulting in failure to retrieve all expected values from `next()` when `success=true`.
To illustrate the problem clearly, I added a related test in commit efe6a9641318c2616e2c67f697b4c107b0d598d2. This test demonstrates that the existing code does not pass. I then applied a fix in commit ec108ae337754a207ec44133bab72a98bb7b5b63, which resolves the issue.
=> fix: handle framework errors properly in middlewares.

apps/playground/src/app/(examples)/direct/page.tsx, apps/playground/src/app/(examples)/hook/page.tsx, apps/playground/src/app/(examples)/navigation/page.tsx, apps/playground/src/app/(examples)/optimistic-hook/addtodo-form.tsx, packages/next-safe-action/src/action-builder.ts, packages/next-safe-action/src/hooks.types.ts, packages/next-safe-action/src/index.types.ts
Code in this PR brings back the always defined safe action result, so users can destructure the result object, and access its optional properties directly. This is because `next/navigation` functions don't trigger an `undefined` result anymore, so everything works as expected now.
=> refactor: make safe action result always defined

apps/playground/src/app/(examples)/hook/deleteuser-action.ts, packages/next-safe-action/src/action-builder.ts, packages/next-safe-action/src/index.types.ts, packages/next-safe-action/src/validation-errors.ts
Code in this PR adds the ability to override the validation error message, when the `throwValidationErrors` option is used at the action level, using an optional async function called `overrideErrorMessage`, that returns the overridden error message, instead of the default one.
=> feat(validation-errors): add `overrideErrorMessage` function to `throwValidationErrors`
